name: release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write
  id-token: write
  attestations: write
  
jobs:
  call-test:
    uses: ./.github/workflows/test.yml
  release-please:
    needs:
    - call-test
    permissions:
      contents: write
      pull-requests: write
    uses: ./.github/workflows/release-please.yml
  check-output:
    if: github.repository == 'slawo/go-hello'
    runs-on: ubuntu-latest
    needs:
    - release-please
    steps:
    - run: echo "${{ needs.release-please.outputs.release_created }}"
    - run: echo "${{ needs.release-please.outputs.tag_name }}"
    - run: echo "${{ needs.release-please.outputs }}"
  release-artifacts:
    needs:
    - release-please
    if: ${{ needs.release-please.outputs.release_created }}
    permissions:
      contents: write
      packages: write
      id-token: write
      attestations: write
    uses: ./.github/workflows/release-artifacts.yml
    with:
      release-version: ${{ needs.release-please.outputs.tag_name }}
    secrets: inherit